name: Laravel Tests
on:
  push:
    branches:
      - dev

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: eshopSystem
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Fix permissions
        run: sudo chown -R $USER:$USER $HOME/.composer

      - name: Install dependencies
        run: composer install --no-scripts

      - name: Allow apt-get to run
        run: sudo rm -f /var/lib/dpkg/lock-frontend

      - name: Update apt cache
        run: sudo apt-get update

      - name: Install PostgreSQL client
        run: sudo apt-get install postgresql-client -y

      - name: Create PostgreSQL database
        env:
          PGPASSWORD: eshopSystem
        run: createdb -h localhost -U admin -e admin

      - name: Copy .env file
        run: cp .env.initial .env  # Zmeníme z .env.example na .env.initial

      - name: Generate application key
        run: php artisan key:generate

      - name: Wait for PostgreSQL
        run: |
          until pg_isready -h localhost -p 5432 -U postgres; do sleep 1; done

